spring:
  application:
    name: rabbitmq-message
  rabbitmq:
    host: localhost
    port: 5672
    username: panli
    password: 666666

server:
  port: 9876

# To enable RabbitMQ plugin management with localhost:15672
#   - .\rabbitmq-plugins.bat enable rabbitmq_management

