server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Incarnation-p-lee/spring-cloud-example-config
          searchPaths: micro-service-config
          username:
          password:

    bus:
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: panli
    password: 666666

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
